# This configuration is intended for development purpose
version : '3.8'
services :
  zookeeper :
    image : docker.io/bitnami/zookeeper:3.8
    container_name : bs-msg-kafka-dev-consuming-hello-zookeeper
    restart : unless-stopped
    environment :
      ZOOKEEPER_CLIENT_PORT : 2181
      ZOOKEEPER_TICK_TIME : 2000
      ALLOW_ANONYMOUS_LOGIN : yes
  kafka :
    image : docker.io/bitnami/kafka:3.3
    container_name : bs-msg-kafka-dev-consuming-hello-broker
    restart : unless-stopped
    depends_on :
      - zookeeper
    ports :
      - "29092:29092"
    environment :
      KAFKA_BROKER_ID : 1
      KAFKA_CFG_ZOOKEEPER_CONNECT : bs-msg-kafka-dev-consuming-hello-zookeeper:2181
      KAFKA_CFG_ADVERTISED_LISTENERS : PLAINTEXT://bs-msg-kafka-dev-consuming-hello-broker:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_CFG_LISTENERS : PLAINTEXT://:9092,PLAINTEXT_KAFKA://:9091
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE : true
      ALLOW_PLAINTEXT_LISTENER : yes
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP : PLAINTEXT:PLAINTEXT,PLAINTEXT_KAFKA:PLAINTEXT

  prometheus :
    container_name : bs-msg-kafka-dev-consuming-hello-prometheus
    image : prom/prometheus:v2.37.1
    volumes :
      - ./docker/prometheus/:/etc/prometheus/
    command :
      - '--config.file=/etc/prometheus/prometheus.yml'
    # On MacOS, remove next line and replace localhost by host.docker.internal in docker/prometheus/prometheus.yml and
    # docker/grafana/provisioning/datasources/datasource.yml
    network_mode : 'host' # to test locally running service
  grafana :
    container_name : bs-msg-kafka-dev-consuming-hello-grafana
    image : grafana/grafana:8.5.13
    volumes :
      - ./docker/grafana/provisioning/:/etc/grafana/provisioning/
    environment :
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    # On MacOS, remove next line and replace localhost by host.docker.internal in docker/prometheus/prometheus.yml and
    # docker/grafana/provisioning/datasources/datasource.yml
    network_mode : 'host' # to test locally running service
