build :
  description : '@project.description@'
  relative-path : ${SWAGGER_UI_RELATIVE_PATH:}
  version : '@project.version@'

git :
  commit : '@git.commit.id@'
  build_time : '@git.build.time@'

info :
  app :
    name : '@project.name@'
    description : '@project.description@'
    version : '@project.version@'
    git_commit : ${git.commit}
    build_time : ${git.build_time}

spring :
  application :
    name : bs-msg-kafka-consuming-hello
  jackson :
    default-property-inclusion : NON_NULL
  lifecycle :
    timeout-per-shutdown-phase : ${TIMEOUT_PER_SHUTDOWN:20s}

  kafka :
    consumer :
      bootstrap-servers : ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
      value-deserializer : org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset : earliest
      properties :
        schema.registry.url : ${KAFKA_SCHEMA_REGISTRY_URL:http://localhost:8081}
        basic.auth.credentials.source : SASL_INHERIT
        security.protocol : ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
        sasl.mechanism : SCRAM-SHA-512
        sasl.jaas.config : "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"${KAFKA_USERNAME}\" password=\"${KAFKA_PASSWORD}\";"
        isolation.level : read_committed
        spring.json.trusted.packages : '*'
      group-id : ${KAFKA_CONSUMERS_GROUP:consuming-hello}
    producer :
      bootstrap-servers : ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
      value-serializer : org.springframework.kafka.support.serializer.JsonSerializer
      properties :
        schema.registry.url : ${KAFKA_SCHEMA_REGISTRY_URL:http://localhost:8081}
        basic.auth.credentials.source : SASL_INHERIT
        security.protocol : ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
        sasl.mechanism : SCRAM-SHA-512
        sasl.jaas.config : "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"${KAFKA_USERNAME}\" password=\"${KAFKA_PASSWORD}\";"
        spring.json.add.type.headers : false
    admin :
      properties :
        bootstrap.servers : ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
        security.protocol : ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
        sasl.mechanism : SCRAM-SHA-512
        sasl.jaas.config : "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"${KAFKA_USERNAME}\" password=\"${KAFKA_PASSWORD}\";"

  devtools :
    add-properties : false
    restart :
      enabled : false
    livereload :
      enabled : false
logging :
  level :
    ROOT : ${LOGGING_LEVEL_ROOT:INFO}
    org.zalando.logbook.Logbook : TRACE

management :
  health :
    livenessstate :
      enabled : true
    readinessstate :
      enabled : true
  info :
    env :
      enabled : true
  server :
    add-application-context-header : true
  endpoints :
    enabled-by-default : false
    web :
      path-mapping :
        health : actuator/health
        prometheus : metrics
        info : info
      base-path : /
      exposure :
        include : health, prometheus, info, openapi, swagger-ui
  endpoint :
    health :
      enabled : true
      show-details : always
      probes :
        enabled : true
    prometheus :
      enabled : true
    info :
      enabled : true

server :
  port : ${SERVER_PORT:8080}
  shutdown : graceful

embedded :
  kafka :
    enabled : false
    docker-image-version : 6.2.4

ujar :
  kafka :
    create-topics-on-startup : ${KAFKA_CREATE_TOPICS_ON_STARTUP:true}
    topics :
      hello-world :
        name : ${KAFKA_TOPIC_HELLO_WORLD:hello.world}
        partitions : ${KAFKA_TOPIC_PARTITIONS_HELLO_WORLD:2}
        retention : ${KAFKA_TOPIC_RETENTION_HELLO_WORLD:30m}
    error-handling :
      dead-letter :
        retention : 1d
        suffix : .DLT
      backoff :
        initial-interval : 500ms
        max-interval : 2s
        max-retries : 4
        multiplier : 1.5

springdoc :
  show-actuator : true
  swagger-ui :
    config-url : ${SWAGGER_UI_RELATIVE_PATH:/}v3/api-docs/swagger-config
    url : ${SWAGGER_UI_RELATIVE_PATH:/}v3/api-docs
